---

- name: Apply packages updates
  ansible.builtin.dnf:  # noqa: package-latest
    name: "*"
    state: latest
    update_cache: true
    exclude: "{{ edpm_update_exclude_packages }}"
  tags:
    - edpm_update
