---
- name: Update openvswitch packages without stopping the service
  become: true
  tags:
    - update
    - ovs
  ansible.builtin.shell: >
    dnf update -y openvswitch --setopt=tsflags=noscripts
  register: update_ovs_result
  failed_when: update_ovs_result.rc != 0

- name: Reload openvswitch service
  become: true
  tags: 
    - reload
    - ovs
  ansible.builtin.systemd_service:
    name: openvswitch.service
    daemon_reload: true
    state: reloaded
    masked: false
  when:
    - edpm_ovs_reload_after_update
    - '"Nothing to do." not in update_ovs_result.stdout_lines'